name: Mise a jour Foot Sync
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installer les modules
        run: pip install requests
      - name: Executer le script
        run: python script.py
      - name: Sauvegarder la page web
        run: |
          git config --global user.name 'FootSync-Bot'
          git config --global user.email 'bot@footsync.com'
          git add index.html
          git commit -m "Mise à jour automatique" || exit 0
          git push
